

RDIO_KEY : heb8db942wmxe4zwh7uts8wa
RDIO_SECRET : vDRswYWKG8

LASTFM_KEY : b23503ef3550247f1b3a0854b89dcba0
LASTFM_SECRET : 627e409d895437ca92f12e30794bb03a

AMZN_KEY: AKIAJYE24OHNGKPIYQVA
AMZN_SECRET: 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
AMZN_TAG: jakelevineme-20

MEMCACHIER_USERNAME: c2d4a5
MEMCACHIER_PASSWORD: 2b1f5d634f
MEMCACHIER_SERVERS: mc4.dev.ec2.memcachier.com